name: ups-microservice
services:
- name: web
  # Option 1: Use buildpack (current setup)
  # environment_slug: python
  # Option 2: Use container registry (uncomment below and comment above)
  image:
    registry_type: DOCR
    repository: ups-microservice
    tag: latest
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /health
    port: 8000
  envs:
  - key: UPS_CLIENT_ID
    type: SECRET
  - key: UPS_CLIENT_SECRET
    type: SECRET
  - key: UPS_ENVIRONMENT
    value: production