version: "1"
pipelines:
  - name: ups-microservice-pipeline:1.0.1
    description: build a release for deployment
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=master
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    events:
      - "github:crystalcommerce/ups-rate-service:pull_request.merged"
      - "github:crystalcommerce/ups-rate-service:tag.created"
    jobs:
      - name: ups-microservice-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - unzip
          - python
          - wget
          - tar
        steps:
          - set +u
          - wget https://cto-ai-builder-dev.s3.amazonaws.com/cto-build.tar.gz
          - tar -xzvf cto-build.tar.gz
          - hash -p "$(pwd)"/cto-build/cto-build cto-build
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO
          - cd $REPO && ls -asl
          - git fetch && git checkout $REF
          - cto-build --dockerfile=Dockerfile --org=$ORG --repo=$REPO --branch=$REF --tag=registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF --type=DO --img

  - name: ups-microservice-pipeline-local:1.0
    description: build a UPS Microservice release for deployment locally (useful for big images)
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=CUSTOM
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    jobs:
      - name: ups-microservice-local-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - unzip
          - python
          - wget
          - tar
          - jq
        steps:
          - set +u
          - wget https://cto-ai-builder-dev.s3.amazonaws.com/cto-build.tar.gz
          - tar -xzvf cto-build.tar.gz
          - hash -p "$(pwd)"/cto-build/cto-build cto-build
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO
          - cd $REPO && ls -asl
          - RAW_BRANCH_LIST=$(curl -s -X GET -H "Accept:application/vnd.github+json" -H "Authorization:token $GITHUB_TOKEN" https://api.github.com/repos/$ORG/$REPO/branches | jq '.[] | .name' | head -n 20 | awk '{print}' ORS="' '" | sed 's/"//g')
          - echo "ux prompt list '$RAW_BRANCH_LIST$REF' --message='Select the repository branch to build' --name='reference'" >> /tmp/ux.sh && chmod 755 /tmp/ux.sh
          - if [ "${REF}" = "CUSTOM" ]; then REF=`/tmp/ux.sh`; fi
          - if [ "${REF}" = "CUSTOM" ]; then REF=`ux prompt input --message='Enter the repository branch to build' --name='reference'`; fi && echo "Going to checkout $REF"
          - git fetch && git checkout $REF
          - cto-build --dockerfile=Dockerfile --org=$ORG --repo=$REPO --branch=$REF --tag=registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF --type=DO --img
