version: "1"
pipelines:
  - name: ups-microservice-pipeline:1.0.1
    description: build a release for deployment
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=master
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    events:
      - "github:crystalcommerce/ups-rate-service:pull_request.merged"
      - "github:crystalcommerce/ups-rate-service:tag.created"
    jobs:
      - name: ups-microservice-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - docker
        steps:
          - set +u
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO
          - cd $REPO
          - git fetch && git checkout $REF
          - echo $DO_TOKEN | docker login registry.digitalocean.com -u $DO_TOKEN --password-stdin
          - docker build --pull -t registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF .
          - docker push registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF

  - name: ups-microservice-pipeline-local:1.0
    description: build a UPS Microservice release for deployment locally (useful for big images)
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=CUSTOM
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    jobs:
      - name: ups-microservice-local-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - docker
          - jq
          - curl
        steps:
          - set +u
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO
          - cd $REPO
          - RAW_BRANCH_LIST=$(curl -s -X GET -H "Accept:application/vnd.github+json" -H "Authorization:token $GITHUB_TOKEN" https://api.github.com/repos/$ORG/$REPO/branches | jq '.[] | .name' | head -n 20 | awk '{print}' ORS="' '" | sed 's/"//g')
          - echo "ux prompt list '$RAW_BRANCH_LIST$REF' --message='Select the repository branch to build' --name='reference'" >> /tmp/ux.sh && chmod 755 /tmp/ux.sh
          - if [ "${REF}" = "CUSTOM" ]; then REF=`/tmp/ux.sh`; fi
          - if [ "${REF}" = "CUSTOM" ]; then REF=`ux prompt input --message='Enter the repository branch to build' --name='reference'`; fi && echo "Going to checkout $REF"
          - git fetch && git checkout $REF
          - echo $DO_TOKEN | docker login registry.digitalocean.com -u $DO_TOKEN --password-stdin
          - docker build --pull -t registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF .
          - docker push registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF
