version: "1"
pipelines:
  - name: ups-microservice-pipeline:1.0.1
    description: build a release for deployment
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=master
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    events:
      - "github:crystalcommerce/ups-rate-service:pull_request.merged"
      - "github:crystalcommerce/ups-rate-service:tag.created"
    jobs:
      - name: ups-microservice-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - unzip
          - python
          - wget
          - tar
        steps:
          - wget https://github.com/digitalocean/doctl/releases/download/v1.102.0/doctl-1.102.0-linux-amd64.tar.gz
          - tar xf ./doctl-1.102.0-linux-amd64.tar.gz
          - ./doctl version
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO #only remote
          - cd $REPO && ls -asl #only remote
          - RAW_BRANCH_LIST=`git branch -r --sort=-committerdate | grep -v HEAD | head -n 20 | sed 's:.*/::' | awk '{print}' ORS="' '"` #only remote
          - echo "ux prompt list '$RAW_BRANCH_LIST$REF' --message='Select the repository branch to build' --name='reference'" >> /tmp/ux.sh && chmod 755 /tmp/ux.sh  #only remote
          - if [ "${REF}" = "CUSTOM"  ]; then REF=`/tmp/ux.sh`; fi #only remote
          - if [ "${REF}" = "CUSTOM" ]; then REF=`ux prompt input --message='Enter the repository branch to build' --name='reference'`; fi && echo "Going to checkout $REF" #only remote
          - git fetch && git checkout $REF #only remote
          - cto-build --dockerfile=Dockerfile --org=$ORG --repo=$REPO --branch=$REF --tag=registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF --type=DO --img

  - name: ups-microservice-pipeline-local:1.0
    description: build a UPS Microservice release for deployment locally (useful for big images)
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - STACK_TYPE=do-k8s
        - ORG=crystalcommerce
        - REPO=ups-rate-service
        - REF=CUSTOM
      secrets:
        - GITHUB_TOKEN
        - DO_TOKEN
        - UPS_CLIENT_ID
        - UPS_CLIENT_SECRET
        - API_KEY
    jobs:
      - name: ups-microservice-local-build-job
        description: Build UPS Microservice image
        packages:
          - git
          - unzip
          - python
          - wget
          - tar
          - jq
        steps:
          - whoami
          - wget https://github.com/digitalocean/doctl/releases/download/v1.102.0/doctl-1.102.0-linux-amd64.tar.gz
          - tar xf ./doctl-1.102.0-linux-amd64.tar.gz
          - ./doctl version
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$ORG/$REPO #only remote
          - cd $REPO && ls -asl #only remote
          - RAW_BRANCH_LIST=`git branch -r --sort=-committerdate | grep -v HEAD | head -n 20 | sed 's:.*/::' | awk '{print}' ORS="' '"` #only remote
          - echo "ux prompt list '$RAW_BRANCH_LIST$REF' --message='Select the repository branch to build' --name='reference'" >> /tmp/ux.sh && chmod 755 /tmp/ux.sh  #only remote
          - if [ "${REF}" = "CUSTOM"  ]; then REF=`/tmp/ux.sh`; fi #only remote
          - if [ "${REF}" = "CUSTOM" ]; then REF=`ux prompt input --message='Enter the repository branch to build' --name='reference'`; fi && echo "Going to checkout $REF" #only remote
          - git fetch && git checkout $REF #only remote
          - cto-build --dockerfile=Dockerfile --org=$ORG --repo=$REPO --branch=$REF --tag=registry.digitalocean.com/$ORG/$REPO-$STACK_TYPE:$REF --type=DO --img
